export const projectsData = [
  {
    id: 'varnam',
    name: 'Varnam',
    subtitle: 'Integrated Event Registration & Management Platform',
    github: 'https://github.com/sneha-marimuthu/Varnam',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Full-stack event platform for seamless registration and organizer operations.',
    fullDescription:
      'Built a full-stack event management platform for technical and cultural fests, enabling seamless participant registration, event tracking, and organizer management.',
    impact: ['Handled 20+ concurrent users during registrations', 'Reduced manual organizer work by 70% through automated Excel workflows'],
    features: ['Secure user authentication and multi-event registration', 'Real-time event dashboard with schedules, rules, and venue updates', 'Admin panel for registration tracking, Excel export, and student verification', 'Mobile-first responsive UI for smooth on-spot registrations'],
    techStack: ['React.js', 'Tailwind CSS', 'Node.js', 'Express.js', 'MySQL', 'PostgreSQL', 'MongoDB', 'Docker', 'GitHub'],
  },
  {
    id: 'premiumbills',
    name: 'PremiumBills',
    subtitle: 'Enterprise Invoice Management & Billing System',
    github: 'https://github.com/sneha-marimuthu/PremiumBills',
    live: 'https://premiumbills.onrender.com',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Automated billing platform with invoice PDF generation and validation.',
    fullDescription:
      'Developed a full-stack billing platform during internship at CoirPlus to automate invoice generation and streamline financial workflows.',
    impact: ['Reduced invoice processing time by 85%', 'Supported 50+ invoices/hour', 'Achieved 99.9% billing accuracy', 'Delivered within 15 days'],
    features: ['Automated generation of professional PDF invoices', 'Excel-integrated workflow', 'Centralized client and billing management', 'Secure financial validation logic'],
    techStack: ['HTML', 'CSS', 'React.js', 'Flask', 'Python', 'Google Cloud', 'GitHub'],
  },
  {
    id: 'mcet-connect',
    name: 'MCET Connect',
    subtitle: 'Role-Based Query Management System',
    github: 'https://github.com/sneha-marimuthu/QueryAPP',
    backend: 'https://github.com/sneha-marimuthu/LoginCRUD',
    image: 'https://images.unsplash.com/photo-1521898284481-a5ec348cb555?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Academic query platform for students, faculty, and administrators.',
    fullDescription:
      'Developed a multi-role academic query platform to streamline communication between students, faculty, and administrators.',
    impact: ['Improved query resolution speed by 60%', 'Reduced cross-platform development time by 40%'],
    features: ['RBAC authentication system', 'Real-time query tracking', 'CRUD operations and profile management', 'Cross-platform support'],
    techStack: ['Flutter', 'Dart', 'Spring Boot', 'Java', 'MySQL', 'Docker', 'Figma', 'GitHub'],
  },
  {
    id: 'stockanalyzer',
    name: 'StockAnalyzer',
    subtitle: 'Real-Time Market Analytics Platform',
    github: 'https://github.com/sneha-marimuthu/StockAnalyzer',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Market tracking, analysis, and portfolio monitoring platform.',
    fullDescription: 'Built a full-stack stock analytics platform for market tracking, technical analysis, and portfolio monitoring.',
    impact: ['Data refresh latency under 2 seconds', 'Processed 5+ years historical data under 500ms'],
    features: ['Live stock tracking', 'Interactive financial charts', 'Price alert system', 'Portfolio simulation'],
    techStack: ['React.js', 'Flask', 'Pandas', 'NumPy', 'Financial APIs', 'GitHub'],
  },
  {
    id: 'railtrack',
    name: 'RailTrack',
    subtitle: 'Dynamic Train Scheduling System',
    github: 'https://github.com/sneha-marimuthu/Train_Traffic_Management_Coder',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Railway scheduling system with conflict-aware rescheduling logic.',
    fullDescription: 'Developed a railway traffic management platform for train scheduling optimization and conflict handling.',
    impact: ['Rescheduling decisions under 800ms', 'Reduced delay propagation by 45%'],
    features: ['Dynamic timetable management', 'Automated rescheduling', 'Real-time train visualizations', 'Dispatcher dashboard'],
    techStack: ['React.js', 'Flask', 'GitHub'],
  },
  {
    id: 'londonhotel',
    name: 'LondonHotel',
    subtitle: 'Hotel Management REST API',
    github: 'https://github.com/sneha-marimuthu/LondonHotel',
    image: 'https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Spring Boot backend for hotel booking and reservation workflows.',
    fullDescription: 'Developed a Java Spring Boot REST API for managing hotel operations, including room bookings, customer records, and reservation workflows.',
    impact: [],
    features: ['Hotel, room, and booking management APIs', 'Reservation creation, cancellation, and tracking', 'Secure CRUD operations with validation', 'RESTful backend architecture'],
    techStack: ['Spring Boot', 'Java', 'SQL', 'JPA', 'HTML', 'Maven', 'GitHub'],
  },
  {
    id: 'cloudvendor',
    name: 'CloudVendor',
    subtitle: 'Vendor Management REST API',
    github: 'https://github.com/sneha-marimuthu/LondonHotel',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Scalable CRUD-first vendor management API architecture.',
    fullDescription: 'Developed a Spring Boot REST API for managing vendor records with structured CRUD workflows and scalable backend architecture.',
    impact: [],
    features: ['Vendor CRUD APIs', 'RESTful endpoint architecture', 'JSON-based data handling', 'Validation and exception handling'],
    techStack: ['Spring Boot', 'Java', 'SQL', 'JPA', 'Maven', 'GitHub'],
  },
  {
    id: 'music-player',
    name: 'Music Player',
    subtitle: 'Full-Stack Audio Streaming Platform',
    github: 'https://github.com/sneha-marimuthu/Music-Player',
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Interactive music app with playlist and streaming capabilities.',
    fullDescription: 'Developed a full-stack music streaming platform with playlist management, real-time audio playback, and interactive controls.',
    impact: [],
    features: ['Audio playback controls', 'Playlist management', 'Audio upload and streaming', 'Responsive music player UI'],
    techStack: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'MongoDB', 'GitHub'],
  },
  {
    id: 'weather-app',
    name: 'Weather App',
    subtitle: 'Real-Time Weather Forecast Platform',
    github: 'https://github.com/sneha-marimuthu/Weather-App',
    live: 'https://sneha-marimuthu.github.io/Weather-App/',
    image: 'https://images.unsplash.com/photo-1492011221367-f47e3ccd77a0?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Responsive weather app fetching live data from external APIs.',
    fullDescription: 'Developed a responsive weather application that fetches and displays city\'s live weather data using openweather[external] API.',
    impact: [],
    features: ['Real-time city weather search', 'Dynamic weather rendering', 'REST API integration', 'Responsive interface'],
    techStack: ['HTML', 'CSS', 'JavaScript', 'Weather API', 'GitHub'],
  },
  {
    id: 'todo-spring',
    name: 'To-Do List Using Spring',
    subtitle: 'Task Management REST API',
    github: 'https://github.com/sneha-marimuthu/To-Do-List-using-Spring',
    image: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Task management backend with persistent CRUD operations.',
    fullDescription: 'Developed a Spring Boot task management application with CRUD operations and persistent backend architecture.',
    impact: [],
    features: ['Task CRUD operations', 'Task status management', 'RESTful APIs', 'Database persistence with Spring Data JPA'],
    techStack: ['Spring Boot', 'Java', 'SQL', 'JPA', 'Maven', 'GitHub'],
  },
]
